language: go
go:
- 1.9
install:
- make deps
- go get -t ./...
script:
- make test
- make vet
- make lint
env:
  global:
  - secure: "WCA3AaTy49RQ7ME+fdWHwMAWl6/+MYrLP5NnP7bnuIw5UKDv4Ougo4GSAkd566p7SnK4wXGThr6/LnRzse8tfae4f9kKHmHo1+8qXKeEjyRcwkVLdJvWgpvhrhheSQm717Aq0WgJAqIYjVz57oHvRx8qvECYlzsk3fIWLe6gilR2Bj+aO9ujEV+lwGSXbkkEmbfN8wm56SiLdufd6HVOwKk1s3Dxl7cOmLUKO/0DTJ7h9Fy7HyPDOlLxTKQtUx69153o2lhdzM0wNZUoIWO5UvZ6sj5/Zl305LtoKCNwb0ejSIxUjBYxS8TN9OJZXMsvVZa2ETzfyRuz12rhgoyOEbHrLuZ8AddVvYXcEXj/kdatcJchR+rqoHhb8L3oawjYsImnOsFEu6aU62Bp3SePfXIx3Qym9pV3/ukOAzxexods9HSQ0s2JJ3vYXRIyG5oOy6Ls5nyUj01saB3XpsEl3ypIcSPSm9dgLV8/D/D+gPSzGMdsFlLtDEU9A6qEjUiFbRYJrlL8G84GZgG4Fbhj6MXMjvZphiqDTlAiBbGcE4eVMxfhdWW2RhmL/zywDu1bDTr7Gl4jCYoZZYOxbP5iISTPAQmuFULCxzNdhJX+oMHhDBZtIoOvbCXwQ2QhZ8eJLx43yANsIJ67maUyDJ/2yZlTb81EpOXWCwd2RqXFbKE="
deploy:
- script:
  - make release
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME = linux"
