language: go
go:
- 1.9
install:
- make deps
- go get -t ./...
script:
- make test
- make vet
- make lint
env:
  global:
  - secure:
deploy:
- script:
  - make release
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME = linux"
